/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "examples/autotest-validate/autotest-validate.h"
#include <stdbool.h>

/*=======Structure Used By Test Runner=====*/
struct UnityRunTestParameters
{
  UnityTestFunction func;
  const char* name;
  UNITY_LINE_TYPE line_num;
};

/*=======External Functions This Runner Calls=====*/
extern void Test_assignment_validate_setUp(void);
extern void Test_assignment_validate_tearDown(void);
extern void test_assignment_validate();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void Test_assignment_validate_setUp(void) {}

/*=======Teardown (stub)=====*/
void Test_assignment_validate_tearDown(void) {}

/*=======Test Reset Options=====*/
void Test_assignment_validate_resetTest(void);
void Test_assignment_validate_resetTest(void)
{
  Test_assignment_validate_tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  Test_assignment_validate_setUp();
}
void Test_assignment_validate_verifyTest(void);
void Test_assignment_validate_verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        Test_assignment_validate_setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        Test_assignment_validate_tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int Test_assignment_validate_main(void);
int Test_assignment_validate_main(void)
{
  UnityBegin("/home/shantanu3107/Desktop/ased-assignments./COMPLETED_ASSIGNMENTS/assignment2/assignment-autotest/test/assignment1/Test_assignment_validate.c");

  int number_of_tests = 1;
  struct UnityRunTestParameters run_test_params_arr[number_of_tests];

  run_test_params_arr[0].func = test_assignment_validate;
  run_test_params_arr[0].name = "test_assignment_validate";
  run_test_params_arr[0].line_num = 9;

  for (int i = 0; i < number_of_tests; i++)
  {
    run_test(run_test_params_arr[i].func, run_test_params_arr[i].name, run_test_params_arr[i].line_num);
  }

  return UNITY_END();
}
